// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrTrv351Fc5QTZWJvLouIwWWwRdX8bOYE',
    appId: '1:26010506432:web:2bef8b2194680c49cb0925',
    messagingSenderId: '26010506432',
    projectId: 'psikolog-39791',
    authDomain: 'psikolog-39791.firebaseapp.com',
    storageBucket: 'psikolog-39791.appspot.com',
    measurementId: 'G-0LCXGJVW7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPJbYzo5Twfg5TvjNAAF-RbFBGYuHm5xM',
    appId: '1:26010506432:android:2da0dd87e6aeaed7cb0925',
    messagingSenderId: '26010506432',
    projectId: 'psikolog-39791',
    storageBucket: 'psikolog-39791.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyhkJz_cvPQCWbMDDVjA2SVRGlFGonOM',
    appId: '1:26010506432:ios:f6ad75afcf470e47cb0925',
    messagingSenderId: '26010506432',
    projectId: 'psikolog-39791',
    storageBucket: 'psikolog-39791.appspot.com',
    iosClientId: '26010506432-0cptr81nprgdb64eifj8lantemt5hm81.apps.googleusercontent.com',
    iosBundleId: 'com.example.psikolog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyhkJz_cvPQCWbMDDVjA2SVRGlFGonOM',
    appId: '1:26010506432:ios:f6ad75afcf470e47cb0925',
    messagingSenderId: '26010506432',
    projectId: 'psikolog-39791',
    storageBucket: 'psikolog-39791.appspot.com',
    iosClientId: '26010506432-0cptr81nprgdb64eifj8lantemt5hm81.apps.googleusercontent.com',
    iosBundleId: 'com.example.psikolog',
  );
}
